import Foundation

/// Pure parsed view of the app's build metadata, sourced from `Info.plist`.
///
/// `version` and `build` come from the standard `CFBundleShortVersionString` /
/// `CFBundleVersion` keys; `commit` comes from `GitCommitHash`, which is
/// injected via `BuildInfo.xcconfig` (generated by the `build-info` Taskfile
/// step) and substituted into `Info.plist` by Xcode before code signing.
/// `name` comes from `CFBundleDisplayName`, falling back to `CFBundleName`,
/// then to a sensible literal when both are missing/empty (keeps the About
/// view useful in test/preview bundles whose plist isn't the shipping plist).
///
/// `commit` is `nil` when the key is missing, empty, whitespace-only, or equal
/// to the sentinel `"unknown"` — all four cases mean "no real hash available",
/// and the About view collapses to omit the commit line in that case.
struct BuildInfo: Equatable {
    /// Sensible literal fallback when the bundle has no display/short name —
    /// only reachable from synthetic dictionaries (test bundles); shipping
    /// bundles always provide `CFBundleName`.
    static let defaultAppName = "TrafficWand"

    let name: String
    let version: String
    let build: String
    let commit: String?

    init(infoDictionary: [String: Any]) {
        self.name = Self.resolveName(from: infoDictionary)
        self.version = (infoDictionary["CFBundleShortVersionString"] as? String) ?? ""
        self.build = (infoDictionary["CFBundleVersion"] as? String) ?? ""

        let rawCommit = infoDictionary["GitCommitHash"] as? String
        let trimmed = rawCommit?.trimmingCharacters(in: .whitespacesAndNewlines)
        if let trimmed, !trimmed.isEmpty, trimmed != "unknown" {
            self.commit = trimmed
        } else {
            self.commit = nil
        }
    }

    private static func resolveName(from dict: [String: Any]) -> String {
        if let displayName = dict["CFBundleDisplayName"] as? String, !displayName.isEmpty {
            return displayName
        }
        if let bundleName = dict["CFBundleName"] as? String, !bundleName.isEmpty {
            return bundleName
        }
        return defaultAppName
    }

    /// Reads the running bundle's `Info.plist`. Exposed as a function (not a
    /// computed property) because every call performs `Bundle.main` I/O — a
    /// property would suggest a constant value, which this is not.
    static func current() -> BuildInfo {
        .init(infoDictionary: Bundle.main.infoDictionary ?? [:])
    }
}
